
services:
  app:
    build:
      context: .              # Laravel project files
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www
      - /var/www/node_modules
    container_name: laravel_app
    working_dir: /var/www
    ports:
      - "9000:9000"           # PHP-FPM port
      - "5173:5173"           #Vite
    command: php-fpm

  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    container_name: laravel_nginx

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    container_name: laravel_db
    volumes:
      - db_data:/var/lib/mysql    # Persist MySQL data

volumes:
  db_data:    
